FROM node:18-alpine as builder

WORKDIR /app

COPY ./Auditt.Web/package*.json ./
COPY ./Auditt.Web/tsconfig*.json ./
COPY ./Auditt.Web/vite.config.ts ./
COPY ./Auditt.Web/public/ ./public/
COPY ./Auditt.Web/src/ ./src/

RUN npm install
RUN npm run build

FROM nginx:alpine

COPY ./Auditt.Web/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
